#!/bin/sh
if [ -f /etc/enigma2/cachecockpit.db ]; then
	mv /etc/enigma2/cachecockpit.db /etc/enigma2/cachecockpit.db.bak
fi
touch /etc/enigma2/.cachecockpit

echo "***********************************"
echo "*          CacheCockpit           *"
echo "*               by                *"
echo "*          dream-alpha            *"
echo "***********************************"
echo ""
echo "CacheCockpit plugin installed successfully."
echo "Please restart DreamOS now!"
echo ""
exit 0
