#!/bin/sh
if [ "$1" = "remove" ]; then
	rm -rf /usr/script/CacheCockpit

	echo "CacheCockpit plugin removed successfully."
else
	find /usr/lib/enigma2/python/Plugins/SystemPlugins/CacheCockpit -type f -name "*.pyo" -exec rm -f {} \; > /dev/null 2>&1
fi
exit 0
